name: Lint

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
  AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}
  REVALIDATION_TOKEN: ${{ secrets.REVALIDATION_TOKEN }}
  REVALIDATE_URL: ${{ secrets.REVALIDATE_URL }}
  REDIS_URL: ${{ secrets.REDIS_URL }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'yarn'
      - run: yarn
      - run: yarn lint